portfolio/urls.py
from django.urls import path
from .views import home, skills, contact_view, about, python

app_name = 'portfolio'
urlpatterns = [
    path('', home, name='home'),
    path('skills/', skills, name='skills'),
    path('prolang/python', python, name='python'),
    path('contact/', contact_view, name='contact'),
    path('about/', about, name='about'),
]

portfolionthumo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('__reload__', include('django_browser_reload.urls')),
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Your Name', 'class': 'form-input bg-black border border-gray-600 rounded-lg w-full p-2 text-white'})
        )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'placeholder': 'Your Email', 'class': 'form-input bg-black border border-gray-600 rounded-lg w-full p-2 text-white'})
        )
    comment = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Message', 'class': 'form-textarea bg-black border border-gray-600 rounded-lg w-full p-2 text-white h-20'})
        )

portfolio/views.py
from django.shortcuts import render,redirect
from django.core.mail import send_mail
from django.conf import settings
from .forms import ContactForm
import logging


logger = logging.getLogger(__name__)

#contactform view
def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            comment = form.cleaned_data['comment']
            try:
                send_mail(
                    f"New contact form submission from {name}",
                    comment,
                    email,
                    [settings.DEFAULT_FROM_EMAIL],
                    fail_silently=False,
                )
                return redirect('contact')
            except Exception as e:
                logger.error(f"Error Sending Email: {e}")
                return render(request, 'portfolio/contact.html', {'form':form, 'error': 'There was an error sending your message. Please try later.'})
    else:
        form = ContactForm()

    return render(request, 'portfolio/contact.html', {'form': form})

# home view.
def home(request):
    return render(request, 'portfolio/home.html')


def about(request):
    return render(request, 'portfolio/about.html')

#skills view
def skills(request):
    return render(request, 'portfolio/skills.html')

#skills sub-views
def python(request):
    return render(request, 'portfolio/python.html')


#def intouch(request):
#    return render(request, 'portfolio/contact.html')

portfolio/templates/portfolio/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Nthumo</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/dist/styles.css' %}">
</head>
<body class="bg-zinc-900">
    <div class="grid container mx-auto gap-4 pt-4">
        <div class="text-center text-white text-4xl md:text-4xl lg:text-5xl bg-zinc-800 h-40 flex items-center justify-center rounded-lg">
            <h1 class="flex items-center gap-4 underline underline-offset-8 decoration-sky-700 pt-4">
                <img src="{% static 'images/me' %}" alt="Nthumo" class="border-4 rounded-full border-gray-300 shadow-lg" style="width: 120px; height: 120px;">
                <span class="text-gray-300">WHO I <span class="text-sky-700">AM?</span> </span>
                
            </h1>
        </div>
        <div class="flex text-white text-wrap bg-zinc-800 p-4 pb-4 rounded-lg whitespace-normal lg:h-fit">          
            <div>
                <p class="mb-4">
                    Hi, I'm Emmanuel Nthumo Mutinda, a passionate full-stack software developer with a strong foundation in Python and other programming languages. Currently, I am pursuing my Bachelor's degree in Computer Science at Murang'a University of Technology.
                </p>
                <!--
                <p class="mb-4">
                    My academic journey has equipped me with a solid understanding of software development principles and practices. Courses such as Software Development, Data Structures and algorithms, and Web Application Development have been instrumental in honing my skills and knowledge.
                </p>
                -->
                <p class="mb-4">
                    As a full-stack developer, I am proficient in a variety of technologies and tools. My expertise includes Python, Django, JavaScript, React, HTML, CSS, and SQL. <!-- I have successfully completed several projects, including Project 1, Project 2, and Project 3, which demonstrate my ability to build robust and scalable web applications.-->
                </p>
                <p class="mb-4">
                    I am particularly interested in developing innovative solutions that leverage modern technologies to solve real-world problems. My goal is to continually improve my skills and contribute to impactful projects in the tech industry. I am eager to collaborate with like-minded professionals and organizations that share my passion for technology and innovation.
                </p>
                <p class="mb-4">
                    Beyond my technical abilities, I am known for my strong problem-solving skills, attention to detail, and ability to work effectively in team settings. I am always eager to learn new technologies and stay updated with industry trends.
                </p>
                <p class="mb-4">
                    Thank you for visiting my portfolio. Feel free to explore my projects and get in touch with me if you'd like to discuss potential opportunities or collaborations.
                </p>
            </div>
        </div>
    </div>
</body>
</html>

portfolio/templates/portfolio/contact.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Contact</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/dist/styles.css' %}">
    </head>

    <body class="bg-zinc-900 text-white">
        <div class="grid grid-cols-1 gap-4 md:grid-cols-2 px-4 py-8">

            <div class="max-w-lg mx-auto p-8 rounded-lg bg-zinc-800 items-center grid gap-y-4 pt-2">
                <div>
                    <img src="{%static 'images/lapi'%}" alt="Laptop" class="rounded-lg" style="width: 450px; height: 250px;">
                </div>
                
                <div class="bg-zinc-900 h-50 md:h-40 rounded-lg p-4">
                    <h1>If you have any suggestions, project ideas or even just want to say Hello, fell free to reach out.</h1>
                    <br>
                    <h1 class="text-orange-400">Click the icon of your choice and you'll find me there:</h1>

                </div>
                <div class="flex gap-4 items-center justify-center bg-white p-2 rounded-lg bottom-0">
                    <a href="https://github.com/Nthumo"><img src="{%static 'images/github'%}" width="35" alt="github" class=""></a>
                    <a href="https://x.com/1_nthumo"><img src="{% static 'images/X'%}" width="35" alt="X" class="rounded-full"></a>
                    <a href="https://wa.me/+254797575799"><img src="{%static 'images/whatsapp'%}" width="35" alt="whatsapp"></a>
                    <a href="tel:+254797575799"><img src="{%static 'images/phone'%}" width="35" alt="phone" class="rounded-full"></a>
                    
                </div>
            </div>

            <div class="max-w-lg mx-auto bg-zinc-800 p-8 rounded-lg shadow-lg">
                <h2 class="md:text-2xl font-bold mb-4 text-white underline underline-offset-8 decoration-double decoration-sky-400">FEEL FREE TO DROP ME A LINE</h2>
                <p class="mb-4">Fell free to reach out through email by filling this form:</p>
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-4">
                        <label for="name" class="sr-only"></label>
                        {{ form.name }}
                    </div>
                    <div class="mb-4">
                        <label for="email" class="sr-only"></label>
                        {{ form.email }}
                    </div>
                    <div class="mb-4">
                        <label for="comment" class="sr-only"></label>
                        {{ form.comment }}
                    </div>
                    <button type="submit" class="bg-sky-400 text-white py-2 px-4 rounded-lg hover:bg-sky-600 hover:border">
                         <span class="text-black font-bold">SEND MESSAGE</span>
                    </button>
                </form>
            </div>
        </div>
    </body>


</html>

portfolio/templates/portfolio/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nthumo Mutinda Portfolio</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/dist/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/dist/anime.css' %}">
    <style>
        .group:hover .hover-text-white {
            color: rgb(31, 10, 224)
        }
        .group:hover .hover-text-black {
            color: #FFFFFF;
        }

        .bebas-neue-regular {
         font-family: "Bebas Neue", sans-serif;
         font-weight: 400;
         font-style: normal;
        }



    </style>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Playwrite+FR+Moderne:wght@100..400&display=swap" rel="stylesheet">

</head>
<body class="bg-black  overflow-hidden text-center">

    <!-- main container-->
    <div class="flex flex-col p-4 h-svh">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-2 h-full w-full">

                <!-- intro section-->
                <div class="p-4 sm:p-6 md:p-8 lg:10 xl:12 flex flex-col justify-center items-center sm:min-h-[150px] min-h-[100px] md:min-h-[200px] gap-4">
                    <p class="block text-gray-300 text-lg md:text-2xl lg:text-3xl">HI THERE! I'M</p>
                    <h1 class="block text-2xl md:text-4xl lg:5xl font-serif font-extrabold text-center text-sky-400">NTHUMO MUTINDA</h1>

        <div class="wrapper">
            <h1 class="overflow-hidden text-wrap block font-mono font-extrabold text-md md:text-lg lg:text-xl text-center pt-2">
                    
                    <span class="word block text-white">SOFTWARE DEVELOPER</span>
                    <span class="word block text-white opacity-25 line-through decoration-red-600">ANIMATOR</span>
                    <span class="word block text-white">SOFTWARE DEVELOPER</span>
                    <span class="word block text-white">GRAPHIC DESIGNER</span>
                    <span class="word block text-white opacity-25 line-through decoration-red-600">VIDEO EDITOR</span>
            </h1>
        </div>

                </div>

                <!--about section-->
                <a href="{% url 'portfolio:about'%}" class="md:l-10 rounded bg-zinc-900 p-4 sm:p-6 md:p-8 lg:p-10 xl:p-12 flex items-center justify-center sm:min-h-[80px] min-h-[100px] md:min-h-[200px] group transform transition-all cursor-pointer hover:scale-95">
                    <div class="">
                        <h2 class="text-2xl md:text-4xl font-extrabold text-center text-white">
                            <span class="hover-text-white">ABOUT</span>
                            <span class="hover-text-black text-blue-800">ME</span>
                        </h2>
                    </div>
                </a>


                <!-- my skills section-->
                <a href="{% url 'portfolio:skills'%}" class="rounded bg-zinc-900 p-4 sm:p-6 md:p-8 lg:p-10 xl:p-12 flex items-center justify-center sm:min-h-[80px] min-h-[100px] md:min-h-[200px] group transition-all transform cursor-pointer hover:scale-95">
                    <div  class="" >
                        <h2 class="text-2xl md:text-4xl font-extrabold text-center text-white">
                            <span class="hover-text-white">MY</span>
                            <span class="text-blue-800 hover-text-black">SKILLS</span>
                        </h2>
                    </div>

                </a>
             

                <!-- get in touch section-->
                <a href="{% url 'portfolio:contact' %}" class="rounded bg-zinc-900 p-4 sm:p-6 md:p-8 lg:p-10 xl:p-12 flex items-center justify-center sm:min-h-[80px] min-h-[100px] md:min-h-[200px] group transition-all cursor-pointer hover:scale-95 transform">
                    <div class="">
                        <h2 class="text-2xl md:text-4xl font-extrabold text-center text-white">
                            <span class="hover-text-white">GET</span>
                            <span class="text-blue-800 hover-text-black">IN TOUCH</span>
                        </h2>
                    </div>
                </a>
            

        </div>
    </div>

    <script>
        // JavaScript for additional interactivity can be added here if needed
    </script>
</body>
</html>

portfolio/templates/portfolio/skills.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>My skills</title>
        
        <link rel="stylesheet" href="{% static 'css/dist/styles.css' %}">

        <style>
            .custom-header {
                display: inline-block;
                width: max-content;
            }
        </style>
    </head>
    <body class="bg-zinc-900 p-4 overflow-auto">

        <!--main container-->
        <div class="grid md:grid-cols-2 gap-4">

            <!--programming languages-->
            <div class="bg-zinc-800 min-h-[100px] text-white text-center rounded-lg">
                <h1>
                    <span class="underline-offset-8 decoration-double decoration-sky-400 underline text-white"> PROGRAMMING LANGUAGES</span>
                    <ul class="grid gap-2 pt-4 p-4 ">
                        <li class="flex gap-4 items-center  block p-2 bg-black hover:border rounded-lg">
                            <img src="{% static 'images/python' %}" width="30" alt="python">
                            Python</li>
                        <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                            <img src="{% static 'images/js' %}" width="30" alt="JavaScript" class="rounded-lg">
                            JavaScript</li>
                        <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                            <img src="{%static 'images/c'%}" width="30" alt="C">
                            C/C++</li>
                        <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                            <img src="{%static 'images/html5'%}" width="30" alt="HTML">
                            HTML</li>
                            
                        <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                            <img src="{%static 'images/css3'%}" width="30" alt="HTML">
                            CSS
                        </li>
                        
                        <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                            <img src="{%static 'images/sql'%}" width="50" alt="">
                            SQL</li>
                    </ul>
                    
                </h1>

            </div>

            <!--frameworks and libraries-->
            <div class="bg-zinc-800 min-h-[100px] h-40 text-white text-center rounded-lg">
                <h1>
                    <span class="underline-offset-8 decoration-double decoration-sky-400 underline text-white">FRAMEWORKS AND LIBRARIES</span>
                    <ul class="grid gap-2 pt-4 p-4">
                        <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                            <img src="{%static 'images/django'%}" width="30" alt="django" class="rounded-lg">
                            Django</li>
                        <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                            <img src="{%static 'images/tailwind'%}" width="30" alt="tailwindcss">
                            Tailwind CSS</li>
                    </ul>
                    
                </h1>
             </div>

            <!--databases-->
             <div class="bg-zinc-800 min-h-[100px] text-white text-center rounded-lg">
                <h1>
                    <span class="text-white underline decoration-double decoration-sky-400 underline-offset-8">DATABASES</span>
                    <ul class="grid gap-2 pt-4 p-4">
                        <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                            <img src="{%static 'images/postgresql'%}" width="30" alt="PostreSQL">
                            PostreSQL</li>
                        <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                            <img src="{%static 'images/sqlite'%}" width="30" alt="SQLite">
                            SQLite</li>
                        <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                            <img src="{%static 'images/mongodb'%}" width="15" alt="MongoDB">
                            MongoDB</li>
                    </ul>
                    
                </h1>
             </div>

             <!--apis and web services-->
             <div class="bg-zinc-800 min-h-[100px] text-white text-center rounded-lg">
                <h1>
                    <span class="text-white underline underline-offset-8 decoration-double decoration-sky-400">APIs AND WEB SERVICES</span>
                    <ul class="grid gap-2 pt-4 p-4">
                        <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">RESTful APIs</li>
                        <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                            <img src="{%static 'images/graphql'%}" width="30" alt="">
                            GraphQl</li>
                        <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">API Intergration</li>
                    </ul>
                    
                </h1>
             </div>

             <!--version control and collaboration-->
             <div class="bg-zinc-800 min-h-[100px] h-40 text-white text-center rounded-lg">
                <h1>
                    <span class="underline underline-offset-8 decoration-double decoration-sky-400">VERSION CONTROL AND COLLABORATION</span>
                    <ul class="grid gap-2 pt-4 p-4">
                        <li class="flex gap-4 items-center block p-2 bg-zinc-900 hover:border rounded-lg">
                            <img src="{%static 'images/git'%}" width="30" alt="Git" class="rounded-lg">
                            Git</li>
                        <li class="flex gap-4 items-center block p-2 bg-zinc-900 hover:border rounded-lg">
                            <img src="{%static 'images/github'%}" width="30" alt="">
                            GitHub</li>
                    </ul>
                    
                </h1>
             </div>

            <!--development tools-->
             <div class="bg-zinc-800 min-h-[100px] text-white text-center rounded-lg">
                <h1 class="">
                    <span class="underline underline-offset-8 decoration-double decoration-sky-400">DEVELOPMENT TOOLS</span>
                    <ul class="grid gap-2 pt-4 p-4">
                        <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                            <img src="{%static 'images/docker'%}" width="30" alt="Docker">
                            Docker</li>
                        <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                            <img src="{%static 'images/kubernetes'%}" width="30" alt="Kubernetes">
                            Kubernetes</li>
                        <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                            <img src="{%static 'images/vscode'%}" width="30" alt="Visual Studio Code" class="rounded-lg">
                            Visual Studio Code</li>
                    </ul>
                    
                </h1>
             </div>
        </div>
    </body>

</html>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>